### ISSUE TITLE
Update for Raspberry pi 4 ?

### ISSUE THREAD

**Issue by Elrondo46** [kounch/argonone#1]
Can you update it for Rpi4 ?

**Comment by kounch** [comment]
I don’t have one for testing. The installation steps are different from Raspberry Pi 3?

**Comment by Elrondo46** [comment]
no just think about 3 lines
enable_uart=1 in config.txt
i2c-bcm2708
and
add raspberry pi 4 in the bignning of file and point it to another install mode

I will test it because I'll receive it at max 15 days later

**Comment by thegeek1977** [comment]
I got my Argon One case today and since I'm on Manjaro arm wich is Arch based and have no other way to make the case work correctly i decided tp try the suggested fix that Elondo56 posted 

It sorta work. The daemon will start and run and the button work as exspected however if I
shutdown the pi from within the terminal og by selecting shutdown in Cinnamon the pi will shut down but will not turn off. It will shut down correctly and turn off if I shut it down on the power button on the case.

The fan does not work at all. I cannot get it to kick in. Tried it from the original script on Raspian and it kicked in just fine. In Manjaro I cannot get it to kick in at all even if I go to aconone-config and tell it to always be one. If I shut down the daemon and triy to run it manually with 
<code>
sudo /opt/argonone/bin/argononed.py
</code>

I got this error

<code>
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/argonone/bin/argononed.py", line 104, in temp_check
    bus.write_byte(address, block)
AttributeError: 'SMBus' object has no attribute 'write_byte'
</code>

so clearly something went wrong writting to the bus.

I got this relevant lines in my config.txt

<code>
dtparam=i2c_arm=on
dtparam=i2c-1=on
enable_uart=1
</code>

I can easily test again if you do change something so please let me know what I should try or how to fix this. I'll gladly help testing but i'm not a python coder.

But since I want this nice case to work in Arch I'll gladly test if needed.

**Comment by thegeek1977** [comment]
also I forgot to mention that the enable_uart=1 in /boot/config.txt in conjunction with having kgdboc=ttyAMA0,115200 mentioned in /boot/cmdline does crash the kernel (kernel panic) so please check for this if you are planning on automatically ad the uart-option to /boot/config.txt.
I did fix this by removing kgdboc=ttyAMA0,115200 from my /boot/cmdline

**Comment by Elrondo46** [comment]
I think the address is different to call smbus in bcm2708. I will check it in original script when I'll receive the case

**Comment by Elrondo46** [comment]
To fix shutdown from Cinnamon or others you need to configure the button action in your desktop environment. I use Manjaro amd64 since five years :).

**Comment by thegeek1977** [comment]
Naah I think you are misunderstanding. The button on the case are definitely not an ACPI-button after all. It's more like a flip-flop coupled with a MOSFET, feeding the PI via the GPIO 5 volt supply pins when it is asked to be turned on by the user and then cuts off the power to the GPIO when asked by the user or by the script running on the PI so really, you will find nothing in the settings for reacting to the power button.

It is not that it will not shut down if I ask it to it. I shuts down fine but the power isn't cut as it should.
The red led on the PI indicating that it gots power is still lit after the pi shuts off and I have to hold the button to get the hardware in the case to force the power off after the PI is shut down. In Raspian the hardware in the case will automatically cut the power after the pi has shut off, wich are the correct way. I will experiment futher to see if it is something that I will be able to do something about.

Anyway I got the fan to work here is how I dpne it. I changed line 104 in argononed.py to look like this

<code>
bus.write_byte_data(address,0,block)
</code>

and the i of course restart the daemon. Now the fan works as it should and turns on/off as expected. So the only real hassle now is to get the case to cut power to the pi after the shutdown process which is initiated thru software has finished. I'll recon that it might be a identical problem (data no written to the bus correctly)  but we should investigate the poweroff-code futher.

I'll let your guys know if I found something interesting.

**Comment by thegeek1977** [comment]
Sure thing, I fixed that too.
here is how

In /usr/lib/systemd/system-shutdown/argononed-poweroff.py i changed the following.

Line 20
<code>
bus.write_byte_data(0x1a,0,0)
</code>

Line 23
<code>
bus.write_byte_data(0x1a,0,0xFF)
</code>

In fact this was the exact same problem as with the daemon. bus.write_byte is not recognized so instead i tried with bus.write_byte_data ans set a zero as the middle argument. That worked.

I really don't know why bus.write_byte isn't recognized. We should test the new code on real RPI3-hardware to see if everything works back and forth.

Now we just have to wrap all thing up with the suggestions of Elrondo46, figuring out how to avoid kernel panic with the uart-setting  and you can have a final release.

will I be able to do commits to your code here on github or will you wrap it up yourself, dear author?

**Comment by Elrondo46** [comment]
Very thanks to you, that's awesome, I'll test it when I receive this f.... mail package :)

**Comment by kounch** [comment]
The original design of this package was made extracting all the data from the official install script from argonone. Have you checked that source?

**Comment by kounch** [comment]
Regarding the write_bytes error, it looks like a problem with the virtual environment install see here another similar situation:

https://github.com/adafruit/Adafruit_CircuitPython_TSL2591/issues/8

**Comment by kounch** [comment]
> Sure thing, I fixed that too.
> here is how
> 
> In /usr/lib/systemd/system-shutdown/argononed-poweroff.py i changed the following.
> 
> Line 20
> ` bus.write_byte_data(0x1a,0,0) `
> 
> Line 23
> ` bus.write_byte_data(0x1a,0,0xFF) `
> 
> In fact this was the exact same problem as with the daemon. bus.write_byte is not recognized so instead i tried with bus.write_byte_data ans set a zero as the middle argument. That worked.
> 
> I really don't know why bus.write_byte isn't recognized. We should test the new code on real RPI3-hardware to see if everything works back and forth.
> 
> Now we just have to wrap all thing up with the suggestions of Elrondo46, figuring out how to avoid kernel panic with the uart-setting and you can have a final release.
> 
> will I be able to do commits to your code here on github or will you wrap it up yourself, dear author?

I will prepare a feature branch for pi4. When it is ready, send your pull requests there

**Comment by Elrondo46** [comment]
I will help to test these improvements if you want

**Comment by kounch** [comment]
This is the location of the script

`https://download.argon40.com/argon1.sh`

**Comment by Elrondo46** [comment]
You will laugh, I receive the package tomorow

**Comment by kounch** [comment]
I can see that they have made some changes. I will update the main branch accordingly.

**Comment by thegeek1977** [comment]
You're so very welcome Elrondo46 I'm just happy if I could possible help someone (and possible myself too). Hope you got your case about now. it is awesome and does a VERY brillant job cooling the pi down to workable temperatures, even when the pi is under very heavy load.

However I found another problem with the code. Althougt it will turn on/off the fan it seems that the speed from 1-100 is all the same. So somehow there is no difference from the various speeds. Though the fan will run on either 0 or100% (i believe). something needs to be done about this. While it is not a major problem (the cooling works best at full speed of cause) the noise it makes, running full speed could be for some people.

Kounch: If it is really so, why don't we just install the needed extensions system wide. I mean, I know about Python local enviroments and how it is sure best practice to install extensions locallly to avoid further updates to break things (remenber. I'm not a python-developer so I could be all wrong) but since it looks like we just have to deal with 2 or max 3 extensions I believe that there is not much to really break Why don't we just install the 2-3 extensions system wide to avoid this problem. If this is just stupid then please educate me cause I simply really don't know enough about this?

**Comment by kounch** [comment]
> Kounch: If it is really so, why don't we just install the needed extensions system wide. I mean, I know about Python local enviroments and how it is sure best practice to install extensions locallly to avoid further updates to break things (remenber. I'm not a python-developer so I could be all wrong) but since it looks like we just have to deal with 2 or max 3 extensions I believe that there is not much to really break Why don't we just install the 2-3 extensions system wide to avoid this problem. If this is just stupid then please educate me cause I simply really don't know enough about this?

Using a virtual environment not only keeps the system clean, it also gives you isolation so it's more difficult that, for example, a system wide update, or another package installing an incompatible version of the modules, could break your software.

**Comment by kounch** [comment]
> You will laugh, I receive the package tomorow

Can you confirm the the official script for Raspberry Pi 4 is hosted in the following link?

`https://download.argon40.com/argon1.sh`

**Comment by thegeek1977** [comment]
Yeah that url to the script is the one mentioned in the printed manual so, yeah I, for my part, pretty much can confirm this 110%

**Comment by Elrondo46** [comment]
All patches fully functional tested it. You can correct these

**Comment by D-argo** [comment]
Hi  Elrondo46  adn others,
Can someone write me, or send me, what exactly I need to do or change and all what I need to do to force argonone fun hat work on my Raspberry pi 4b in Manjaro ARM 64bit? Original procedure doesnt work for me. I will be very grateful to you. Thanks

**Comment by Elrondo46** [comment]
Please go to https://github.com/Elrondo46/argonone
It's my repo all patched, if you want to test it and report me if it's all good :)

**Comment by D-argo** [comment]
Hey, thanks a lot.
But its not perfect...
First I found, you forgot on this:
 In /usr/lib/systemd/system-shutdown/argononed-poweroff.py i changed the following.

Line 20
bus.write_byte_data(0x1a,0,0)

It was there still bus.write_byte(0x1a, 0)
when I correct it, fan works after reboot BUT if I shutdown and turn on again, fan is in defaulth mode (50%) and fan temperature controll doesnt turn on after manjaro boot.
Fun temperature controll enable only when I Manjaro rebooted, NOT if I start Manjaro from poweroff state.

Where is problem?

**Comment by Elrondo46** [comment]
I think this is a Manjaro problem, I don't have any issues with ArchARM. Maybe another service conflicts with argononed service when reboot

**Comment by DragonflyNet67** [comment]
I installed it as described on Manjaro 4.19.89-2 on a Raspberry Pi4B Rev. 1.1
Everything works fine (Power button and Fan as described in the manual), except the 2 desktop Icons were missing, which are included in the original Script from Argon (Fan Configuration and Uninstall). I created them manually onto my desktop and copied the 2 icons from the original script to  the desktop. I zipped all 4 files from my current system:
[argonone.zip](https://github.com/kounch/argonone/files/4027376/argonone.zip)

In order to get RPi.GPIO work without problems i followed the instruction here: [https://forum.manjaro.org/t/rpi4-gpio/101189/19](url) 
and
[https://raspberrypi.stackexchange.com/questions/40105/access-gpio-pins-without-root-no-access-to-dev-mem-try-running-as-root/40106#40106](url). 

Since these changes (settings) get lost on reboot or when a pi-firmware update is installed I created a service which executes a bash script doing the stuff mentioned in those links.

I had to do this also for the I2C stuff. See [https://lexruee.ch/setting-i2c-permissions-for-non-root-users.html](url)

Also for this I created a service to run a bash script once at boot.

Hope this helps if anyone has problems with the argon one script for power button or the fan.

**Comment by hectorkvs** [comment]
I've tried this :

git clone https://github.com/Elrondo46/argonone.git
cd argonone
sudo pacman -S base-devel (to install some missing packages)
makepkg -si
sudo systemctl enable argononed.service
sudo reboot

Everything installed properly, can access argonone-config from terminal, but fan still doesn't work..:-(

**Comment by hectorkvs** [comment]
tommy@RPi4-Manjaro ~]$ sudo systemctl status argononed.service
[sudo] password for tommy:
● argononed.service - Argon One Fan and Button Service
Loaded: loaded (/usr/lib/systemd/system/argononed.service; enabled; vendor preset: disabled)
Active: failed (Result: exit-code) since Thu 2020-03-05 14:19:49 CET; 48s ago
Process: 1197 ExecStart=/opt/argonone/bin/python3 /opt/argonone/bin/argononed.py (code=exited, status=1/FAILURE)
Main PID: 1197 (code=exited, status=1/FAILURE)

Mar 05 14:19:49 RPi4-Manjaro systemd[1]: argononed.service: Scheduled restart job, restart counter is at 5.
Mar 05 14:19:49 RPi4-Manjaro systemd[1]: Stopped Argon One Fan and Button Service.
Mar 05 14:19:49 RPi4-Manjaro systemd[1]: argononed.service: Start request repeated too quickly.
Mar 05 14:19:49 RPi4-Manjaro systemd[1]: argononed.service: Failed with result 'exit-code'.
Mar 05 14:19:49 RPi4-Manjaro systemd[1]: Failed to start Argon One Fan and Button Service.
[tommy@RPi4-Manjaro ~]$

Don't know how to fix it...any help appreciated

**Comment by hectorkvs** [comment]
Needed to install yay -S raspberrypi-userland-aarch64-git...works fine now..thanks anyway

**Comment by kounch** [comment]
Tired of waiting for an updated Raspberry Pi 4 without the USB-C issues, i don't think that i wil order one.

At this moment, i don't think that i will dedicate any more time to this project, but you can fork and add any functionalities as you like.
